export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registrtation'
export const CRYPTOCURRENCIES_ROUTE = '/cryptocurrencies'
export const TRACKING_ROUTE = '/tracking'
export const TRACKING_CRYPTOCURRENCIES_ROUTE = '/tracking_cryptocurrenciesController'